AWSTemplateFormatVersion: '2010-09-09'
Description: CodeBuildProject Cloudformation Template

Parameters:
  GithubUserName:
    Description: Github username
    Type: String
    Default: reysmerwvr
  GithubRepoName:
    Description: Github repository name
    Type: String
    Default: docker-for-frontends
  StackOutputPrefix:
    Description: Stack Output Prefix
    Type: String
    Default: DffCbStack

Resources:
  CodeBuildSourceCredential:
    Type: AWS::CodeBuild::SourceCredential
    Properties:
      AuthType: PERSONAL_ACCESS_TOKEN
      ServerType: GITHUB
      Token: '{{resolve:secretsmanager:github-token}}'

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${StackOutputPrefix}-CodeBuildProject
      Source:
        Type: GITHUB
        Location: !Sub https://github.com/${GithubUserName}/${GithubRepoName}.git
        GitCloneDepth: 1
        ReportBuildStatus: true
        Auth:
          Type: OAUTH
          Resource: !Ref CodeBuildSourceCredential
      Artifacts:
        Type: S3
        Location: !ImportValue DffS3Stack-ArtifactBucketName
        Path: artifacts
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:6.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
      ServiceRole: !ImportValue DffIamStack-CodeBuildServiceRoleArn

Outputs:
  CodeBuildProjectArn:
    Value: !Ref CodeBuildProject
    Export:
      Name: !Sub ${StackOutputPrefix}-CodeBuildProjectArn