AWSTemplateFormatVersion: '2010-09-09'
Description: "CodeBuildProject Cloudformation Template"

Parameters:
  StackOutputPrefix:
    Description: Stack Output Prefix
    Type: String
    Default: DffCbStack

Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${StackOutputPrefix}-CodeBuildProject'
      Source:
        Type: "CODEPIPELINE"
      Artifacts:
        Type: "CODEPIPELINE"
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/standard:6.0'
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: "AWS_ACCOUNT_ID"
            Value: !Ref AWS::AccountId
          - Name: "AWS_DEFAULT_REGION"
            Value: !Ref AWS::Region
      ServiceRole: !ImportValue DffIamStack-CodeBuildServiceRoleArn

Outputs:
  CodeBuildProjectArn:
    Value: !Ref CodeBuildProject
    Export:
      Name: !Sub '${StackOutputPrefix}-CodeBuildProjectArn'
