AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/yourbucket/templates/s3-buckets.yaml'

  CloudFrontStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/yourbucket/templates/cloudfront.yaml'

  IAMRolesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/yourbucket/templates/iam-roles.yaml'

  CodeBuildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/yourbucket/templates/codebuild.yaml'

  CodePipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/yourbucket/templates/codepipeline.yaml'
