AWSTemplateFormatVersion: '2010-09-09'
Description: "Master stack"

Resources:
  SecretStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/cf-templates-1rkt1bxdxoosl-eu-west-1/docker-for-frontends/secrets-manager.yml'

  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/cf-templates-1rkt1bxdxoosl-eu-west-1/docker-for-frontends/s3-buckets.yml'

  IAMRolesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/cf-templates-1rkt1bxdxoosl-eu-west-1/docker-for-frontends/iam-roles.yml'
    DependsOn: S3Stack

  EBApplicationStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/cf-templates-1rkt1bxdxoosl-eu-west-1/docker-for-frontends/elastic-beanstalk.yml'
    DependsOn: IAMRolesStack

  CodeBuildStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/cf-templates-1rkt1bxdxoosl-eu-west-1/docker-for-frontends/codebuild.yml'
    DependsOn: EBApplicationStack

  CodePipelineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/cf-templates-1rkt1bxdxoosl-eu-west-1/docker-for-frontends/codepipeline.yml'
    DependsOn: CodeBuildStack
