AWSTemplateFormatVersion: '2010-09-09'
Description: Github Token Secret Cloudformation Template

Resources:
  GithubTokenSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: github-token
      Description: Github Token
      SecretString: REPLACE THIS WITH YOUR TOKEN
      Tags:
        - Key: Environment
          Value: Dev
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete