AWSTemplateFormatVersion: '2010-09-09'
Description: "Create Github Token Secret in AWS Secrets Manager"

Resources:
  MySecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: "github-token"
      Description: "Github Token"
      SecretString: "REPLACE THIS WITH YOUR TOKEN"
      Tags:
        - Key: "Environment"
          Value: "Dev"