AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-artifacts'
      VersioningConfiguration:
        Status: Enabled

  HostingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-hosting'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      AccessControl: PublicRead

Outputs:
  ArtifactBucketName:
    Value: !Ref ArtifactBucket
    Export:
      Name: !Sub '${AWS::StackName}-ArtifactBucketName'

  HostingBucketName:
    Value: !Ref HostingBucket
    Export:
      Name: !Sub '${AWS::StackName}-HostingBucketName'
