name: Deploy Frontend
on:
  push:
    branches:
      - master

env:
  ELASTIC_BEANSTALK_APPLICATION_NAME: DffEbStack-ElasticBeanstalkApplication
  ELASTIC_BEANSTALK_ENVIRONMENT_NAME: DffEbStack-ElasticBeanstalkEnvironment
  ELASTIC_BEANSTALK_BUCKET_NAME: elasticbeanstalk-eu-west-1-051826698387
  ELASTIC_BEANSTALK_REGION: eu-west-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-for-frontends -f Dockerfile.dev .
      - run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/docker-for-frontends npm run test -- --coverage

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.ELASTIC_BEANSTALK_APPLICATION_NAME }}
          environment_name: ${{ env.ELASTIC_BEANSTALK_ENVIRONMENT_NAME }}
          version_label: ${{ github.sha }}
          region: ${{ env.ELASTIC_BEANSTALK_REGION }}
          deployment_package: deploy.zip
          existing_bucket_name: ${{ env.ELASTIC_BEANSTALK_BUCKET_NAME }}
