AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub '${AWS::StackName}-pipeline'
      RoleArn: !ImportValue CodePipelineServiceRoleArn
      ArtifactStore:
        Type: S3
        Location: !ImportValue ArtifactBucketName
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                Owner: 'your-github-username'
                Repo: 'your-repo-name'
                Branch: 'main'
                OAuthToken: '{{resolve:secretsmanager:github-token}}'
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ProjectName: !ImportValue CodeBuildProjectArn
              RunOrder: 1
